/**
 * Pure (vscode-free) builders for the code-plan → Claude Code handoff.
 *
 * Once a unit's code plan is approved, the plugin does not write source code
 * itself — implementation belongs to an interactive Claude Code session that
 * works under the repository's own conventions and gates. The bridge is a
 * committed, auditable brief (`construction/<unit>/handoff.md`) plus a short
 * launch prompt that points the session at it.
 */

export interface HandoffUnit {
  id: string;
  title: string;
  description?: string;
  jiraKey?: string;
}

export interface HandoffInput {
  unit: HandoffUnit;
  /** Workspace-relative docs folder, e.g. "aidlc-docs". */
  docsPath: string;
  /** Docs-relative paths of the unit's approved artifacts, in read order. */
  artifacts: string[];
  /** Branch the implementation session must work on. */
  branchName: string;
}

/** Docs-relative path of a unit's handoff brief. */
export function handoffRelPath(unitId: string): string {
  return `construction/${unitId}/handoff.md`;
}

/** Kebab-case, ascii-folded, length-capped slug for branch names. */
export function slugify(text: string, maxLength = 40): string {
  const slug = text
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  if (slug.length <= maxLength) {
    return slug;
  }
  const cut = slug.slice(0, maxLength);
  const lastDash = cut.lastIndexOf("-");
  return (lastDash > 0 ? cut.slice(0, lastDash) : cut).replace(/-+$/, "");
}

/** `feature/<KEY>-<slug>` when the unit is Jira-linked, `feature/<slug>` else. */
export function branchNameFor(unit: HandoffUnit): string {
  const slug = slugify(unit.title) || slugify(unit.id) || "unit";
  return unit.jiraKey ? `feature/${unit.jiraKey}-${slug}` : `feature/${slug}`;
}

/**
 * One-liner passed to the `claude` CLI. Must stay safe inside double quotes in
 * every shell (PowerShell, bash, cmd): no `"`, `$`, backticks or backslashes.
 */
export function launchPrompt(handoffWorkspacePath: string): string {
  const path = handoffWorkspacePath.replace(/\\/g, "/");
  return (
    `Read ${path} and execute the handoff it describes: implement the ` +
    `approved AI-DLC code plan for this unit of work, honoring the ` +
    `repository conventions and gates.`
  );
}

/** The committed handoff brief — the contract for the implementation session. */
export function buildHandoffMarkdown(input: HandoffInput): string {
  const { unit, docsPath, artifacts, branchName } = input;
  const key = unit.jiraKey;
  const heading = key ? `${unit.title} (${key})` : unit.title;
  const ticketBit = key ? `, tracked as **${key}**,` : "";

  const artifactLines = artifacts.map((rel, i) => {
    const label =
      i === 0 ? " — **the plan to execute**; everything else is context" : "";
    return `- \`${docsPath}/${rel}\`${label}`;
  });

  const commitRule = key
    ? `Use this repository's commit conventions and carry the ticket key ` +
      `(e.g. \`type(scope): description (${key})\`).`
    : `Use this repository's commit conventions.`;
  const prRule = key
    ? `Open a pull request whose title carries **${key}**; do NOT merge it — ` +
      `merging belongs to the project's gates, reviewers, or automation.`
    : `Open a pull request for review; do NOT merge it — merging belongs to ` +
      `the project's gates, reviewers, or automation.`;

  return `# Handoff — ${heading}

_Generated by the AIDLC Tracker when this unit's code plan was approved. This
brief is the contract between the AI-DLC design cycle and the implementation
session. The audit log records the handoff; the dashboard tracks the branch,
PRs and checks${key ? ` by the ticket key ${key}` : ""}._

## Mission

Implement the unit of work **"${unit.title}"**${ticketBit} exactly as
specified by its approved code plan. The plan is the source of truth: if
reality forces a deviation, make the smallest one that works and list every
deviation explicitly in your final report and in the PR description.
${unit.description ? `\n> ${unit.description.trim().replace(/\n/g, "\n> ")}\n` : ""}
## Read first — approved AI-DLC artifacts

${artifactLines.join("\n")}

## Ground rules

1. This repository's own conventions and gates (CLAUDE.md, skills, hooks,
   CODEOWNERS) take precedence over this brief wherever they conflict.
2. Work on a dedicated branch created from the default branch:
   \`${branchName}\`. Never commit to the default branch directly.
3. ${commitRule}
4. Write tests for the new code and run the project's build and test suites
   before pushing.
5. ${prRule}

## Definition of done

- The code plan is implemented, or every deviation is documented.
- Build and tests are green locally and in CI.
- A pull request is open with a description covering scope, deviations from
  the plan, and test evidence.

## Report back

End the session with a summary: what was implemented, deviations from the
plan, test results, and the PR URL.
`;
}
